Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,14 +24,24 @@ jobs:
         with:
           flutter-version: '3.x'
 
-      - name: Build APK
+      - name: Auto Find and Build
         run: |
-          cd flutter_mobile_app
+          echo "Searching for project configuration..."
+          PUB_PATH=$(find . -name "pubspec.yaml" | head -n 1)
+          if [ -z "$PUB_PATH" ]; then
+            echo "Error: pubspec.yaml not found!"
+            exit 1
+          fi
+          
+          PROJ_DIR=$(dirname "$PUB_PATH")
+          echo "Found project at: $PROJ_DIR"
+          
+          cd "$PROJ_DIR"
           flutter pub get
-          flutter build apk --release -t lib/main.dart
+          flutter build apk --release
 
       - name: Upload APK Artifact
         uses: actions/upload-artifact@v4
         with:
           name: sym-app-apk
-          path: flutter_mobile_app/build/app/outputs/flutter-apk/app-release.apk
+          path: '**/build/app/outputs/flutter-apk/app-release.apk'
